### ISSUE TITLE
How to write the equivalent code in C or C++ for nglpy and topopy functionalities?

### ISSUE THREAD

**Issue by senth27** [maljovec/topopy#39]
We are tried using the following python code 

graph = ngl.PrebuiltGraph(edges_tuples)
msc = topopy.MorseSmaleComplex(graph=graph,gradient='steepest',normalization='feature')
msc.build(X, k1)
partitions = msc.get_partitions(persistence=0.8) 

which works ok. But now we need to convert the python code to C or C++, in order to be usable to integrate with other components in a project. 

Are there any equivalent sample code in C  or C++ is available? I understand that the python classes like PreBuildGraph and MorseSmaleComplex are having some part of the algorithm logic in python and then it calls some of the C or C++ API calls from the pyd libraries like _ngl.cp37-win_amd64.pyd and _topology.cp37-win_amd64.pyd.

What is the best way to integrate these functionalities in C/C++ environment? Any suggestions and ideas are most welcome.
Thanks in advance!

**Comment by dmaljovec** [comment]
👋 Thanks for trying it out!

Yeah, the core of this library started in C++ and has gradually shifted to be more compact/generic C code and more specifics in Python. You can construct a Morse-Smale complex by using two Morse complexes which you can get by directly using the `MorseSmaleComplex.h` and `MorseSmaleComplex.cpp` code from this repository. Looking through the python code in [`MorseSmaleComplex.py:build`](https://github.com/maljovec/topopy/blob/master/topopy/MorseSmaleComplex.py#L86-L148), I hope it is somewhat clear how to create C++ version that does the same thing. Basically, you are building two Morse Complexes (one for the stable manifolds and one for the unstable manifolds), and combining their labels to associate each point with both a minimum and maximum. The last step is just to mash their simplification hierarchies into a single sorted list, so you can incrementally merge partitions (cancel critical points). If not, then perhaps the option below would work:

If you want something already packaged up, you could find the Morse-Smale complex class in an earlier iteration of this code that I helped integrate for a different project (I am including all of the relevant files you would need to build it): 
- https://github.com/idaholab/raven/blob/devel/include/contrib/AMSC/AMSC.h
- https://github.com/idaholab/raven/blob/devel/include/contrib/AMSC/UnionFind.h
- https://github.com/idaholab/raven/blob/devel/src/contrib/AMSC.cpp
- https://github.com/idaholab/raven/blob/devel/src/contrib/UnionFind.cpp

(AMSC=Approximate Morse-Smale Complex) YMMV as it has been a long time since I looked at that code, and the idea of moving into this repo was I could maintain it better, so it might have a bit of code rot, though that project is still active, I doubt this piece gets a lot of attention. I am not sure how much the interface changed since pulling this project into its own python library, so you might have to look at it a bit, and if you ask me specific questions it might jog my memory a bit.

The required NGL library in both cases should just be this one:
http://ngraph.org/

My other python package: https://github.com/maljovec/nglpy that this depends on should just be a thin layer around Carlos' and Peter's library provided above.

**Comment by senth27** [comment]
Thank you very much for your response and suggestions!

I would like to try the first approach of using MorseComplex.h and MorseComplex.cpp code with the conversion of py file MorseSmaleComplex.py:build to C++. I will contact you further, if I bump on any troubles along the way. Thanks for your future help!

Just a point, I tried to look into http://ngraph.org/ and the link **ngl-beta.tar.gz** seems to be broken. But I guess it is same as the content from https://github.com/maljovec/nglpy

**Comment by dmaljovec** [comment]
> Just a point, I tried to look into http://ngraph.org/ and the link ngl-beta.tar.gz seems to be broken.

Good to know, it does look like I can find a version of the original source from: https://code.google.com/archive/p/ngl/downloads

> But I guess it is same as the content from https://github.com/maljovec/nglpy

More or less, I believe. I might have added some minor bits to catch some edge cases or make it more compatible with my use cases, but the core logic is largely unchanged.

**Comment by senth27** [comment]
I converted the python code to C++ (with algo template files) and it seems to run ok for the overall flow. However there seems some accuracy issue for the outputs.

In the **MorseSmaleComplex.py -> build()** method, we have the stable and unstable manifold computations.

**stableManifolds._build_for_morse_smale_complex(self, False)
unstableManifolds._build_for_morse_smale_complex(self, True)**

For the unstableManifolds, the "negate" is True. 

I compared the output for **base_partitions** and **merge_sequences** from python and complete C++ versions. 

For **stableManifolds**, the **output matches 100% perfectly** for both  base_partitions and merge_sequences. No problem for stableManifolds!!!

But for **unstableManifolds**, the base_partitions matches perfectly 100%, but the **merge_sequences json output part do NOT match** for Surviving and Saddle index values. I printed and checked all the input passed to 
**MorseComplex<float> morseComplex**(flattenedX, floatY, pMscObj->_gradient, pMscObj->_simplification, floatW, edges, pMscObj->_debug);
The **flattenedX, floatY, edges, gradient, simplification** all matches 100% in python and C++ versions, for the unstableManifolds (after the negate changes).

Now I checked input passed to MorseComplex<float> algo and have no clue on further how to check this issue.

Can you throw some ideas on how to proceed further? (for solving the accuracy issue)

**Comment by dmaljovec** [comment]
Sorry for the slow response. I am going to take a shot in the dark here. I seem to recall the way I did unstable manifolds was to negate the data and reverse the order of the points. Or maybe I did it in place, but you definitely have to break ties differently for the unstable case. That is, if you have a series of points that have the same value, then to apply "simulation of simplicity" correctly, you must break ties in the same way. For instance, if point_n and point_(n+1) have the same function value, then we fall back on the index value to say which is the "higher" value. I believe for my implementation, higher index means higher value, so the algorithm will say that point_(n+1) is higher than point_n. If you negate the data, you want point_(n+1) to be "lower" than point_n, otherwise the two methods will be reporting inconsistent gradient flow.

We should have consistent tie breaks. If two points have the same function value, then you have to consistently call one of them the "higher" value. If you just negate the data, but use the same algorithm then the tie breaks will be inconsistent. 

Perhaps this is your issue? I would check to see if the merge sequence is correct up to a point and then see if that point happens where two local minima have the same function value.

I am not saying this is going to be your problem, but it is a likely failure point.

**Comment by senth27** [comment]
Dear dmaljovec,

I managed to fix some of the issues in the code and now it shows the same result in C++ as Python code.

Also, the speed of the code execution is dramatically improved by a one single change in the MorseComplex.cpp file,
int followChain(int i, std::map<int,int> & merge)

The argument merge in the followChain method should be passed as reference with &. It improves the speed by leaps and bounds.  You may update it in your code base on the repository.

Thank you very much for your kind support all along the way! Highly Appriciated!!! Thanks a lot!

**Comment by dmaljovec** [comment]
> The argument merge in the followChain method should be passed as reference with &. It improves the speed by leaps and bounds. You may update it in your code base on the repository.

Yeah, totally makes sense. This is a simple lookup and there is no reason not to pass by reference. I’ll get that change made. Thanks for the contribution and sorry for the stale reply.

**Comment by maljovec** [comment]
Closed with https://github.com/maljovec/topopy/pull/41
